[project]
name = "must-starter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bandit>=1.9.1",
    "pyjwt>=2.10.1",
    "sqlalchemy>=2.0.44",
]
